import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import "./CampaignRoadmap.css";

// Icon map for timeline phases
const PHASE_ICONS = ["search", "rocket_launch", "trending_up", "flag", "task_alt"];
const STATE_MAP = ["completed", "active", "pending", "pending", "pending"];

const MainBlock = ({ phase, index }) => (
  <div className="main-block">
    <p className="phase-label">PHASE {String(index + 1).padStart(2, "0")}</p>
    <h4>{phase.title}</h4>
    <ul style={{ margin: "8px 0 12px", paddingLeft: "16px" }}>
      {(phase.tasks || []).map((task, i) => (
        <li key={i} style={{ fontSize: "13px", color: "#64748b", lineHeight: "1.6", marginBottom: "4px" }}>
          {task}
        </li>
      ))}
    </ul>
  </div>
);

const DateBlock = ({ phase, index, totalDays }) => {
  const statusMap = [
    { text: "On Track", icon: "check_circle", cls: "success" },
    { text: "Next Phase", icon: "arrow_forward", cls: "active" },
    { text: "Pending", icon: "", cls: "pending" },
  ];
  const s = statusMap[Math.min(index, 2)];

  return (
    <div className="date-block">
      <span className="date-label">ESTIMATED DURATION</span>
      <div className="date-row">
        <span className="date-value">~{Math.ceil(totalDays / 3)} days</span>
        <span className={`status-badge ${s.cls}`}>
          {s.icon && <span className="material-symbols-outlined">{s.icon}</span>}
          {s.text}
        </span>
      </div>
    </div>
  );
};

export default function CampaignRoadmap() {
  const navigate = useNavigate();
  const [roadmap, setRoadmap] = useState(null);
  const [scenario, setScenario] = useState("");

  useEffect(() => {
    const stored = localStorage.getItem("swarm_roadmap");
    const sc = localStorage.getItem("swarm_scenario");
    if (stored) {
      try {
        setRoadmap(JSON.parse(stored));
      } catch {
        setRoadmap(null);
      }
    }
    if (sc) setScenario(sc);
  }, []);

  const phases = roadmap?.phases || [];
  const totalDays = roadmap?.estimated_total_days || 14;

  return (
    <div className="roadmap-page">
      <div className="roadmap-content">
        <header className="page-header">
          <p className="kicker">STRATEGIC BLUEPRINT</p>
          <h2 className="page-title">Campaign Roadmap</h2>
          <p className="page-subtitle">
            {scenario
              ? `AI-generated execution plan for: "${scenario}"`
              : "A structured visual execution path generated by AI based on your simulation."}
          </p>
        </header>

        {/* Execution Summary */}
        <section className="execution-summary-section">
          <div className="summary-card">
            <h3>Execution Summary</h3>
            <div className="summary-stats">
              <div className="stat-item">
                <p className="label">DURATION</p>
                <p className="value">{totalDays} Days</p>
              </div>
              <div className="stat-item">
                <p className="label">PHASES</p>
                <p className="value">{phases.length}</p>
              </div>
              <div className="stat-item">
                <p className="label">SOURCE</p>
                <p className="value" style={{ fontSize: "14px", fontWeight: 700, color: "#0f6cff" }}>
                  AI Generated
                </p>
              </div>
            </div>
            <div className="summary-footer">
              <div className="team-avatars">
                <img src="https://i.pravatar.cc/100?img=1" alt="Team 1" />
                <img src="https://i.pravatar.cc/100?img=2" alt="Team 2" />
                <div className="team-more">+</div>
              </div>
              <button
                className="view-capacity"
                style={{ background: "none", border: "none", cursor: "pointer", color: "#0f6cff", fontSize: "13px", fontWeight: 600 }}
                onClick={() => navigate("/simulation")}
              >
                ← Back to Simulation
              </button>
            </div>
          </div>

          <div className="ai-confidence-card">
            <span className="material-symbols-outlined stars-icon">auto_awesome</span>
            <h2>{phases.length > 0 ? `${phases.length}` : "—"}</h2>
            <p>
              {phases.length > 0
                ? `Execution phases generated by AI across ${totalDays} days`
                : "No roadmap generated yet. Run a simulation first."}
            </p>
          </div>
        </section>

        {/* Central Alternating Timeline */}
        {phases.length > 0 ? (
          <section className="central-timeline">
            {phases.map((phase, index) => {
              const isLeft = index % 2 === 0;
              const icon = PHASE_ICONS[index % PHASE_ICONS.length];
              const state = STATE_MAP[Math.min(index, STATE_MAP.length - 1)];
              return (
                <div className={`timeline-row ${state}`} key={index}>
                  <div className="timeline-col-left">
                    {isLeft ? (
                      <MainBlock phase={phase} index={index} />
                    ) : (
                      <DateBlock phase={phase} index={index} totalDays={totalDays} />
                    )}
                  </div>
                  <div className="timeline-center-icon">
                    <span className="material-symbols-outlined">{icon}</span>
                  </div>
                  <div className="timeline-col-right">
                    {isLeft ? (
                      <DateBlock phase={phase} index={index} totalDays={totalDays} />
                    ) : (
                      <MainBlock phase={phase} index={index} />
                    )}
                  </div>
                </div>
              );
            })}
          </section>
        ) : (
          <div style={{ textAlign: "center", padding: "60px 20px", color: "#94a3b8" }}>
            <span className="material-symbols-outlined" style={{ fontSize: "48px", display: "block", marginBottom: "12px" }}>
              map
            </span>
            <p style={{ fontSize: "16px", fontWeight: 600 }}>No roadmap yet</p>
            <p style={{ fontSize: "13px", marginTop: "4px" }}>
              Run a simulation and click "Generate Roadmap" to build your AI execution plan.
            </p>
            <button
              className="btn-primary"
              style={{ marginTop: "20px" }}
              onClick={() => navigate("/simulation")}
            >
              Go to Simulation
            </button>
          </div>
        )}

        {/* Bottom CTA */}
        {phases.length > 0 && (
          <section className="cta-section">
            <div className="cta-content">
              <h3>Ready to execute?</h3>
              <p>
                This roadmap was generated specifically from your swarm simulation result. Share it with your team or run another scenario to compare.
              </p>
            </div>
            <div className="cta-actions">
              <button className="btn-secondary" onClick={() => navigate("/simulation")}>
                Run Another Simulation
              </button>
              <button className="btn-primary" onClick={() => window.print()}>
                Export Roadmap
              </button>
            </div>
          </section>
        )}
      </div>
    </div>
  );
}