import { useState, useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { motion, useScroll, useSpring } from "framer-motion";
import html2canvas from 'html2canvas'; 
import { jsPDF } from 'jspdf';
import "./CampaignRoadmap.css";

// Icon map for timeline phases
const PHASE_ICONS = ["search", "rocket_launch", "trending_up", "flag", "task_alt"];
const STATE_MAP = ["completed", "active", "pending", "pending", "pending"];

const MainBlock = ({ phase, index }) => (
  <div className="main-block">
    <p className="phase-label">PHASE {String(index + 1).padStart(2, "0")}</p>
    <h4>{phase.title}</h4>
    <ul style={{ margin: "8px 0 12px", paddingLeft: "16px" }}>
      {(phase.tasks || []).map((task, i) => (
        <li key={i} style={{ fontSize: "13px", color: "#64748b", lineHeight: "1.6", marginBottom: "4px" }}>
          {task}
        </li>
      ))}
    </ul>
  </div>
);

const DateBlock = ({ phase, index, totalDays }) => {
  const statusMap = [
    { text: "On Track", icon: "check_circle", cls: "success" },
    { text: "Next Phase", icon: "arrow_forward", cls: "active" },
    { text: "Pending", icon: "", cls: "pending" },
  ];
  const s = statusMap[Math.min(index, 2)];

  return (
    <div className="date-block">
      <span className="date-label">ESTIMATED DURATION</span>
      <div className="date-row">
        <span className="date-value">~{Math.ceil(totalDays / 3)} days</span>
        <span className={`status-badge ${s.cls}`}>
          {s.icon && <span className="material-symbols-outlined">{s.icon}</span>}
          {s.text}
        </span>
      </div>
    </div>
  );
};

export default function CampaignRoadmap() {
  const navigate = useNavigate();
  const [roadmap, setRoadmap] = useState(null);
  const [scenario, setScenario] = useState("");
  
  // Create a ref for the timeline container to track scrolling
  const timelineRef = useRef(null);
  const pdfExportRef = useRef(null);
  
  const handleDownloadPDF = async () => {
    const element = pdfExportRef.current;
    if (!element) return;
    try {
      const canvas = await html2canvas(element, { scale: 2, useCORS: true, backgroundColor: '#f8fafc' });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
      pdf.addImage(imgData, 'PNG', 0, 10, pdfWidth, pdfHeight);
      const targetMonth = localStorage.getItem("target_month") || "Plan";
      pdf.save(`Tauke_Roadmap_${targetMonth}.pdf`);
    } catch (error) {
      console.error("Failed to generate PDF:", error);
      alert("Error generating PDF.");
    }
  };
  
  // Track vertical scroll progress inside the timeline section
  const { scrollYProgress } = useScroll({
    target: timelineRef,
    offset: ["start 80%", "end 60%"] // Starts animating when top hits 80% of screen, finishes near middle
  });
  
  // Add a spring physics effect so the line flows smoothly
  const scaleY = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001
  });

  useEffect(() => {
    const stored = localStorage.getItem("swarm_roadmap");
    const sc = localStorage.getItem("swarm_scenario");
    if (stored) {
      try {
        setRoadmap(JSON.parse(stored));
      } catch {
        setRoadmap(null);
      }
    }
    if (sc) setScenario(sc);
  }, []);

  const phases = roadmap?.phases || [];
  const totalDays = roadmap?.estimated_total_days || 14;

  return (
    <div className="roadmap-page">
      <div className="roadmap-content" ref={pdfExportRef}>
        <header className="page-header">
          <p className="kicker">STRATEGIC BLUEPRINT</p>
          <h2 className="page-title">Campaign Roadmap</h2>
          <p className="page-subtitle">
            {scenario
              ? `AI-generated execution plan for: "${scenario}"`
              : "A structured visual execution path generated by AI based on your simulation."}
          </p>
        </header>

        {/* Execution Summary (Unchanged) */}
        <section className="execution-summary-section">
          <div className="summary-card">
            <h3>Execution Summary</h3>
            <div className="summary-stats">
              <div className="stat-item">
                <p className="label">DURATION</p>
                <p className="value">{totalDays} Days</p>
              </div>
              <div className="stat-item">
                <p className="label">PHASES</p>
                <p className="value">{phases.length}</p>
              </div>
              <div className="stat-item">
                <p className="label">SOURCE</p>
                <p className="value" style={{ fontSize: "14px", fontWeight: 700, color: "#0f6cff" }}>
                  AI Generated
                </p>
              </div>
            </div>
            <div className="summary-footer">
              <div className="team-avatars">
                <img src="https://i.pravatar.cc/100?img=1" alt="Team 1" />
                <img src="https://i.pravatar.cc/100?img=2" alt="Team 2" />
                <div className="team-more">+</div>
              </div>
              <button
                className="view-capacity"
                style={{ background: "none", border: "none", cursor: "pointer", color: "#0f6cff", fontSize: "13px", fontWeight: 600 }}
                onClick={() => navigate("/simulation")}
              >
                ← Back to Simulation
              </button>
            </div>
          </div>

          <div className="ai-confidence-card">
            <span className="material-symbols-outlined stars-icon">auto_awesome</span>
            <h2>{phases.length > 0 ? `${phases.length}` : "—"}</h2>
            <p>
              {phases.length > 0
                ? `Execution phases generated by AI across ${totalDays} days`
                : "No roadmap generated yet. Run a simulation first."}
            </p>
          </div>
        </section>

        {/* Dynamic Alternating Timeline */}
        {phases.length > 0 ? (
          <section className="central-timeline" ref={timelineRef}>
            
            {/* The static gray background line */}
            <div className="timeline-base-line" />
            
            {/* The animated flowing blue line */}
            <motion.div 
              className="timeline-progress-line" 
              style={{ scaleY }} 
            />

            {phases.map((phase, index) => {
              const isLeft = index % 2 === 0;
              const icon = PHASE_ICONS[index % PHASE_ICONS.length];
              const state = STATE_MAP[Math.min(index, STATE_MAP.length - 1)];
              
              return (
                <div className={`timeline-row ${state}`} key={index}>
                  
                  {/* Left Column (Slides in from the left) */}
                  <motion.div 
                    className="timeline-col-left"
                    initial={{ opacity: 0, x: -40 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    viewport={{ once: true, margin: "-100px" }}
                    transition={{ duration: 0.5, ease: "easeOut" }}
                  >
                    {isLeft ? (
                      <MainBlock phase={phase} index={index} />
                    ) : (
                      <DateBlock phase={phase} index={index} totalDays={totalDays} />
                    )}
                  </motion.div>

                  {/* Center Icon (Pops in) */}
                  <motion.div 
                    className="timeline-center-icon"
                    initial={{ opacity: 0, scale: 0 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    viewport={{ once: true, margin: "-100px" }}
                    transition={{ duration: 0.4, delay: 0.1, type: "spring", stiffness: 200 }}
                  >
                    <span className="material-symbols-outlined">{icon}</span>
                  </motion.div>

                  {/* Right Column (Slides in from the right) */}
                  <motion.div 
                    className="timeline-col-right"
                    initial={{ opacity: 0, x: 40 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    viewport={{ once: true, margin: "-100px" }}
                    transition={{ duration: 0.5, ease: "easeOut" }}
                  >
                    {isLeft ? (
                      <DateBlock phase={phase} index={index} totalDays={totalDays} />
                    ) : (
                      <MainBlock phase={phase} index={index} />
                    )}
                  </motion.div>
                </div>
              );
            })}
          </section>
        ) : (
          <div style={{ textAlign: "center", padding: "60px 20px", color: "#94a3b8" }}>
            <span className="material-symbols-outlined" style={{ fontSize: "48px", display: "block", marginBottom: "12px" }}>
              map
            </span>
            <p style={{ fontSize: "16px", fontWeight: 600 }}>No roadmap yet</p>
            <p style={{ fontSize: "13px", marginTop: "4px" }}>
              Run a simulation and click "Generate Roadmap" to build your AI execution plan.
            </p>
            <button
              className="btn-primary"
              style={{ marginTop: "20px" }}
              onClick={() => navigate("/simulation")}
            >
              Go to Simulation
            </button>
          </div>
        )}

        {/* Bottom CTA (Unchanged) */}
        {phases.length > 0 && (
          <section className="cta-section">
            <div className="cta-content">
              <h3>Ready to execute?</h3>
              <p>
                This roadmap was generated specifically from your swarm simulation result. Share it with your team or run another scenario to compare.
              </p>
            </div>
            <div className="cta-actions">
              <button className="btn-secondary" onClick={() => navigate("/simulation")}>
                Run Another Simulation
              </button>
              <button className="btn-primary" onClick={handleDownloadPDF}>
                Export Roadmap
              </button>
            </div>
          </section>
        )}
      </div>
    </div>
  );
}