import { useState, useEffect } from "react";
import { NavLink, useNavigate } from "react-router-dom";
import "./SupervisorClarification.css";
import { API_BASE_URL } from "../config";

const navItems = [
    { label: "Store Setup", icon: "storefront", to: "/store-configuration" },
    { label: "Data Sync", icon: "sync", to: "/data-sync" },
    { label: "Analysis", icon: "insights", to: "/detective-analysis" },
    { label: "Clarification", icon: "forum", to: "/supervisor-clarification", active: true },
    { label: "War Room", icon: "groups", to: "/ai-debate" },
    { label: "Strategy Synthesis", icon: "hub", to: "/final-synthesis" }
];



export default function SupervisorClarification() {
    const navigate = useNavigate();
    useEffect(() => {
        // Clear old answers when starting a new session
        localStorage.removeItem("boss_answers");
    }, []);
    const [notes, setNotes] = useState("");
    const [selectedOption, setSelectedOption] = useState("");
    const [questions, setQuestions] = useState([]);
    const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
    const [isLoading, setIsLoading] = useState(true);
    const [historicalContext, setHistoricalContext] = useState(null);
    const [externalSignal, setExternalSignal] = useState(null);

    const ownerId = localStorage.getItem("owner_id");
    const targetMonth = localStorage.getItem("target_month") || "2026-04";

    useEffect(() => {
        // We no longer need to fetch here! The LoadingPage did it for us.
        const loadSavedData = () => {
            try {
                // 1. Grab the questions the Loading Page saved
                const savedQuestionsStr = localStorage.getItem("boardroom_questions");
                if (savedQuestionsStr) {
                    const parsedQuestions = JSON.parse(savedQuestionsStr);
                    setQuestions(parsedQuestions);
                }

                // 2. Safely parse Historical Context
                const finTrendStr = localStorage.getItem("boardroom_financial_trend");
                if (finTrendStr) {
                    const finTrend = JSON.parse(finTrendStr);
                    
                    // Target the nested total_revenue. Since there is no previous month in the DB output, default it to 0 for now.
                    const currRevenue = Number(finTrend.target_month?.total_revenue) || 0;
                    const prevRevenue = 0; // You will need to calculate this on the backend later if you want the % delta

                    if (prevRevenue > 0 && currRevenue > 0) {
                        const delta = ((currRevenue - prevRevenue) / prevRevenue * 100).toFixed(1);
                        const direction = delta >= 0 ? "increase" : "drop";
                        setHistoricalContext(`Revenue showed a ${Math.abs(delta)}% ${direction} compared to the previous month (RM${Math.round(prevRevenue).toLocaleString()} → RM${Math.round(currRevenue).toLocaleString()}).`);
                    } else if (currRevenue > 0) {
                        setHistoricalContext(`Current month revenue is RM${Math.round(currRevenue).toLocaleString()}. (No historical data from last month to compare against).`);
                    } else {
                        setHistoricalContext("Historical revenue patterns are currently insufficient for a trend comparison.");
                    }
                }

                // 3. Safely parse Supply Signals with a guaranteed fallback
                const diagPatternsStr = localStorage.getItem("boardroom_diagnostic_patterns");
                if (diagPatternsStr) {
                    const diagPatterns = JSON.parse(diagPatternsStr);

                    // Use the actual keys generated by your data
                    const topItems = diagPatterns.top_3_anchors || diagPatterns.new_arrivals || [];

                    if (Array.isArray(topItems) && topItems.length > 0) {
                        // Handle both plain strings (from new_arrivals) and objects (from top_3_anchors)
                        const firstItem = topItems[0];
                        const itemName = typeof firstItem === 'string' ? firstItem : firstItem.item_name;
                        
                        setExternalSignal(`Top performing item: "${itemName}" — monitor stock levels to prevent a supply gap.`);
                    } else if (diagPatterns.alert) {
                        setExternalSignal(diagPatterns.alert);
                    } else {
                        setExternalSignal("Inventory and supply chain levels appear stable based on current data anomalies.");
                    }
                }
            } catch (err) {
                console.error("Failed to parse saved boardroom data:", err);
            } finally {
                // Instantly turn off the loading skeleton!
                setIsLoading(false);
            }
        };

        loadSavedData();
    }, []);

    const handleNext = () => {
        if (currentQuestionIndex < questions.length - 1) {
            setCurrentQuestionIndex(prev => prev + 1);
            setNotes("");
            setSelectedOption(""); // 👈 Clear the button selection!
        }
    };

    const handleSubmit = async (e) => {
        e.preventDefault();

        const existingAnswers = localStorage.getItem("boss_answers") || "";
        const currentQObj = questions[currentQuestionIndex] || {};
        const currentQText = currentQObj.text || "General context";

        // Combine the button choice with any typed notes
        let finalAnswer = selectedOption;
        if (selectedOption === "Other" || notes.trim() !== "") {
            finalAnswer += ` - ${notes}`;
        }

        const combined = existingAnswers
            ? `${existingAnswers}\nQ: ${currentQText}\nA: ${finalAnswer}`
            : `Q: ${currentQText}\nA: ${finalAnswer}`;

        // 2. Save progress locally so it builds up question by question
        localStorage.setItem("boss_answers", combined);

        // 3. Check if there are more questions to answer
        if (currentQuestionIndex < questions.length - 1) {
            handleNext(); // Move to the next question in the UI
        } else {
            // 4. THIS IS THE LAST QUESTION! Send everything to the backend.
            const ownerId = localStorage.getItem("owner_id");
            const targetMonth = localStorage.getItem("target_month"); // Saved earlier

            try {
                const response = await fetch(`${API_BASE_URL}/boardroom/save-context`, {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({
                        merchant_id: ownerId,
                        target_month: targetMonth,
                        boss_context: combined // Send the fully combined Q&A string!
                    })
                });

                const data = await response.json();

                if (data.status === "success") {
                    // 5. Successfully saved to DB! Now we enter the War Room.
                    navigate('/detective-analysis');
                } else {
                    alert("Failed to save answers to database.");
                }
            } catch (error) {
                console.error("Error saving context:", error);
                alert("Network error while saving context.");
            }
        }
    };



    const currentQuestion = questions[currentQuestionIndex];
    const isLastQuestion = currentQuestionIndex === questions.length - 1;
    const totalQuestions = questions.length;

    return (
        <div className="clarification-page">
            <main className="clarification-main">
                <div className="clarification-shell">
                    <header className="clarification-header">
                        <h2 className="page-title">Clarification Request</h2>
                        <p className="page-subtitle">The AI needs your confirmation before proceeding with strategic synthesis.</p>
                    </header>

                    <section className="featured-clarification-card" aria-label="Clarification card">
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
                            <span className="status-pill">
                                <span className="material-symbols-outlined" aria-hidden="true">priority_high</span>
                                Action Required
                            </span>
                            {totalQuestions > 1 && (
                                <span style={{ fontSize: '12px', color: '#64748b', fontWeight: 600 }}>
                                    Question {currentQuestionIndex + 1} of {totalQuestions}
                                </span>
                            )}
                        </div>

                        <h3 className="question-title">
                            {isLoading ? "AI is analyzing your data..." : currentQuestion?.text ?? "Analyzing anomalies in your data..."}
                        </h3>
                        <p className="question-subtitle">Your confirmation improves forecasting accuracy and aligns strategic next actions.</p>

                        <form className="clarification-form" onSubmit={handleSubmit}>
                            <div className="response-card" style={{ padding: '24px', width: '100%', marginBottom: '24px', display: 'block', cursor: 'default' }}>
                                <h4>Select your response:</h4>

                                {/* 1. Render the LLM generated options as premium interactive cards */}
                                <div className="answer-options-grid">
                                    {currentQuestion?.options?.map((opt, idx) => (
                                        <div key={idx} style={{ display: 'flex', flexDirection: 'column' }}>
                                            <label
                                                className={`answer-card ${selectedOption === opt ? 'is-selected' : ''}`}
                                            >
                                                <input
                                                    type="radio"
                                                    name="boss_answer"
                                                    value={opt}
                                                    checked={selectedOption === opt}
                                                    onChange={(e) => setSelectedOption(e.target.value)}
                                                    className="hidden-radio"
                                                />
                                                <div className="custom-radio-circle"></div>
                                                <span className="answer-text">{opt}</span>
                                            </label>

                                            {/* Inline Text Area specifically for "Other" directly below the card */}
                                            {selectedOption === opt && opt === "Other" && (
                                                <div style={{ marginTop: '12px', animation: 'fadeIn 0.2s ease-in-out' }}>
                                                    <textarea
                                                        className="premium-textarea"
                                                        placeholder="Please specify..."
                                                        value={notes}
                                                        onChange={(event) => setNotes(event.target.value)}
                                                        style={{ minHeight: '90px' }}
                                                        autoFocus
                                                    />
                                                </div>
                                            )}
                                        </div>
                                    ))}
                                </div>

                                {/* 2. Fallback if no options are returned by LLM */}
                                {(!currentQuestion?.options || currentQuestion.options.length === 0) && (
                                    <div style={{ marginTop: '16px' }}>
                                        <p style={{ fontSize: '13px', color: '#64748b', marginBottom: '8px', fontWeight: 600 }}>Please specify:</p>
                                        <textarea
                                            className="premium-textarea"
                                            placeholder="Type your context here..."
                                            value={notes}
                                            onChange={(event) => setNotes(event.target.value)}
                                        />
                                    </div>
                                )}
                            </div>

                            <div className="clarification-actions">
                                <button type="submit" className="primary-button" disabled={isLoading}>
                                    {/* 👇 CHANGE THIS LABEL */}
                                    <span>{isLastQuestion ? "View Analysis Dashboard" : "Next Question"}</span>
                                    <span className="material-symbols-outlined" aria-hidden="true">arrow_forward</span>
                                </button>
                            </div>
                        </form>
                    </section>

                    <section className="support-cards" aria-label="Supporting context">
                        <article className="support-card">
                            <div className="support-icon" aria-hidden="true">
                                <span className="material-symbols-outlined">history</span>
                            </div>
                            <div>
                                <h4>Historical Context</h4>
                                <p>
                                    {isLoading
                                        ? "Loading trend analysis..."
                                        : historicalContext || "Revenue pattern analysis in progress."}
                                </p>
                            </div>
                        </article>

                        <article className="support-card">
                            <div className="support-icon" aria-hidden="true">
                                <span className="material-symbols-outlined">inventory_2</span>
                            </div>
                            <div>
                                <h4>Supply Signals</h4>
                                <p>
                                    {isLoading
                                        ? "Loading supply signals..."
                                        : externalSignal || "Supply chain indicators are being analyzed."}
                                </p>
                            </div>
                        </article>
                    </section>
                </div>
            </main>
        </div>
    );
}